In [2]:
import numpy as np
import pandas as pd 
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import StandardScaler

In [3]:
irish = load_iris()
df = pd.DataFrame(irish.data,columns = irish.feature_names)

In [4]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
X = pd.DataFrame(irish.data, columns=irish.feature_names)
y = irish.target

In [9]:
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
scaler = StandardScaler()

In [13]:
scaled_data = scaler.fit_transform(X_train)
scaled_data = scaler.transform(X_test)

In [14]:
model = ElasticNet()
param_grid = {
    'alpha': [0.01, 0.1, 1, 10],
    'l1_ratio': [0.2, 0.5, 0.8]
}
grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5
)

In [22]:
model.fit(X_train, y_train)

ElasticNet()

In [23]:


y_pred = model.predict(X_test)

In [24]:
y_pred

array([1.22281202, 0.51037772, 1.74526384, 1.1753164 , 1.24655983,
       0.4628821 , 0.96158611, 1.31780326, 1.1753164 , 1.03282954,
       1.31780326, 0.43913429, 0.41538648, 0.4628821 , 0.4628821 ,
       1.22281202, 1.48403793, 1.03282954, 1.1753164 , 1.43654231,
       0.48662991, 1.27030764, 0.48662991, 1.43654231, 1.62652479,
       1.34155107, 1.48403793, 1.50778574, 0.43913429, 0.48662991])

In [25]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, y_pred))

0.19795594215652088